name: CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.21.0'

      - name: Set up Minikube
        run: |
          minikube start --driver=docker  # Adjust the driver based on your setup

      - name: Build and Tag Docker Image with Docker Compose
        run: |
          docker-compose -f docker-compose.yml build

      - name: Load Docker Image into Minikube
        run: |
          docker-compose -f docker-compose.yml push

      - name: Deploy to Minikube using Docker Compose
        run: |
          minikube ssh -- docker-compose -f docker-compose.yml up -d

      - name: Wait for Deployment to be Ready
        run: |
          # Add any necessary wait commands here to ensure deployment readiness
          sleep 30  # Example wait time; adjust based on your application's startup time

      - name: Verify Deployment
        run: |
          kubectl get pods  # Example command to verify deployment status

