name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.21.0'

      - name: Set up Minikube
        run: |
          minikube start --driver=docker
          minikube kubectl -- get pods -A

      - name: Build Docker images using Docker Compose
        run: docker-compose -f docker-compose.yml build

      - name: Load Docker Image into Minikube
        run: |
          docker pull localhost:5000/doc-backend:latest  # Ensure latest image is available in Minikube's local Docker registry

      - name: Deploy to Minikube
        run: |
          kubectl set image deployment/doc-backend doc-backend=localhost:5000/doc-backend:latest
          kubectl rollout status deployment/doc-backend
